# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTuW36kv3JFcHmrTm2nw2L5rvAkTBp6C
"""

import os
from fastapi import FastAPI, Depends, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
from . import database, openai_client, auth, router

load_dotenv()

app = FastAPI()

origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://agreeable-desert-0de7e4700.5.azurestaticapps.net"
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router.router)

@app.get("/")
async def root():
    return {"message": "Welcome to the Multimodal GPT Backend"}

@app.get("/api/secure-data")
async def get_secure_data(user: dict = Depends(auth.get_current_user)):
    return {"message": f"This is secure data for user {user.get('preferred_username')}"}